taskflow_analytics:
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: taskflow
      password: taskflow_prod_pass
      database: taskflow_production
      schema: analytics
      threads: 4
  target: dev
